# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8ee03b57412aa3c08849bf00e6daf2d6d8ee266f66413699e26a7b6bd41b073e91bc47d71939e2a5fa464bf870925f1745186cdb9801bf9c875d1d628c246d6

test:
  secret_key_base: b29249fa87e20d46aacef5e483da92903932be403aa9a51fe97ea3bf16453a7a2554beca03886de5afcccb9857b1f439eabbd48cce92f2053b55b12fa9b73f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
