# Site settings
title: Sal Espinosa
email: sespinos@gmail.com
description: >
baseurl: ""
url: "http://s-espinosa.github.io"
twitter_username: sespinos
github_username:  s-espinosa

# Build settings
markdown: kramdown
highlighter: rouge
