// someday/maybe refactor so that each sound is it's own object with on/off colors, patterns... anything else?


//**INITIAL SETUP**//

// setup
var onOff = "off";
var toClearOnOff = 0;
var currentBeat = 0; //out of number of pads
var padsArray = document.getElementsByClassName("pads");
var soundsArray = document.getElementsByClassName("sounds");

// pad colors
var kickOn = "purple";
var kickOnBlink = "#E1AADD";
var snareOn = "orange";
var snareOnBlink = "#FFC58B";
var hatClosedOn = "teal";
var hatClosedOnBlink = "#8FEEEE";
var hatOpenOn = "navy";
var hatOpenOnBlink = "#B9C0F2";

var padBackOn = kickOn;
var padBackOnBlink = kickOnBlink;
var padBackOff = "#A4A6A5";
var padBackOffBlink = "#CFD2D1";

// old nice blue blink
// var padBackOn = "#67A7CE";
// var padBackOnBlink = "#7FC8F6";


// instrument pattern arrays
var kickPattern = [];
var snarePattern = [];
var hatClosedPattern = [];
var hatOpenPattern = [];

// Set kick as initial sound
var activeSound = "kick";
var activeSoundPattern = kickPattern;

// initial beat per minute values
var bpm = 100; //100 beats per minute hard coded for now
var mspbeat = (60*1000)/bpm; //600 milliseconds for each beat
var msp16th = mspbeat/4; //150 milliseconds for each sixteenth note => each pad for 32 pads assuming 2 measures.
// var frequency = 600/(padsArray.length/2);

// add attributes and onclick behavior to pads
setPads();
setSounds();




// Set On button functions
document.getElementById("start").onclick = function() {
	if(onOff === "on") {
		return;
	} else {
		onOff = "on";
		blinkOn();
		// toClearOnOff = setInterval(function(){blinkOn();}, msp16th*padsArray.length);
		toClearOnOff = setInterval(function(){blinkOn();}, msp16th);		
	}
}

// Set the "off" button up.
// if it's clicked and everything is already off (onOff set to "off", do nothing.
// if it's clicked and everything is on, turn it off using the clearInterval function generated by the on button.
document.getElementById("stop").onclick = function() {
	if(onOff === "off") {
		return;
	} else {
		onOff = "off";
		currentBeat = 0;
		changePads(activeSound);
		clearInterval(toClearOnOff);
	}
}







// blinking function for pads
function blinkOn() {
	if (onOff === "off") {
		return;
	} else {
		// console.log(currentBeat + " of " + padsArray.length);
		howToBlink(padsArray[currentBeat],currentBeat);
		howToPlay(currentBeat, kickPattern, "kick");
		howToPlay(currentBeat, snarePattern, "snare");
		howToPlay(currentBeat, hatClosedPattern, "hatClosed");
		howToPlay(currentBeat, hatOpenPattern, "hatOpen");

		if (currentBeat === padsArray.length-1){
			currentBeat = 0;
		} else  {
			currentBeat++;
		}
	}
}

// set delays for blinking behavior on each pad (repeating from the beginning is handled by setInterval in original call from onclick)
var previousBeat = 31;
function howToBlink(padElement, count) {
	if (currentBeat === 0) {
		previousBeat = 31;
	} else {
		previousBeat = currentBeat-1;
	}

	if (activeSoundPattern[currentBeat] === 0) {
		padsArray[currentBeat].style.backgroundColor = padBackOffBlink;
	} else {
		padsArray[currentBeat].style.backgroundColor = padBackOnBlink;
	}
	
	if (activeSoundPattern[previousBeat] === 0) {
		padsArray[previousBeat].style.backgroundColor = padBackOff;
	} else {
		padsArray[previousBeat].style.backgroundColor = padBackOn;
	}
}






// This is where the actual playing of the sound happens.
// Pull the sound name, create a path to the sound,
// access the array for the sound and determine if it's on or off (1 or 0)
// play the sound if it's on, get out of the function if it's off
function howToPlay(count, drumArray, drumSound) {
	var soundPath = "audio/" + drumSound + ".wav"
	// if (drumArray[count] === 1) {
	// 	setTimeout(function() {
	// 		this.snd = new Audio(soundPath);
	// 		snd.play();
	// 	}, msp16th*(count));
	if (drumArray[count] === 1) {
		this.snd = new Audio(soundPath);
		snd.play();
	} else {
		return;
	}
}





// Assign numbers to each of the pads using an attribute.
// Generate an array that's equal to the number of pads for each drum sound.
// Make the pads turn on and off when clicked by assigning an onclick function to each pad.
function setPads() {
	for (i=0; i < padsArray.length; i++) {
		padsArray[i].setAttribute("padNumber", i);
		kickPattern.push(0);
		snarePattern.push(0);
		hatClosedPattern.push(0);
		hatOpenPattern.push(0);
		padsArray[i].onclick = function() {
			var padNumber = this.getAttribute("padNumber");
			if (activeSoundPattern[padNumber] === 0) {
				activeSoundPattern[padNumber] = 1;
				this.style.backgroundColor = padBackOn;
			} else {
				activeSoundPattern[padNumber] = 0;
				this.style.backgroundColor = padBackOff;		
			}
		}	
	}
}




function setSounds() {
	for (i=0; i < soundsArray.length; i++) {
		soundsArray[i].onclick = function() {
			var soundName = this.id;

			if (activeSound === soundName) {
				var soundPath = "audio/" + soundName + ".wav"
				var snd = new Audio(soundPath);
				snd.play();
			} else {
				changePads (soundName);
				var soundPath = "audio/" + soundName + ".wav"
				var snd = new Audio(soundPath);
				snd.play();
			}
		}	
	}
}



function changePads(newPad) {
	var newPadOn = newPad + "On";
	var newPadOnBlink = newPadOn + "Blink";
	var patternToActivate = newPad + "Pattern";


	activeSound = newPad;
	activeSoundPattern = window[patternToActivate];
	padBackOn = window[newPadOn];
	padBackOnBlink = window[newPadOnBlink];


	for (i=0; i<padsArray.length; i++) {
		if (activeSoundPattern[i] === 0) {
			padsArray[i].style.backgroundColor = padBackOff;
		} else {
			padsArray[i].style.backgroundColor = padBackOn;
		}

	}
}