define(function() {

	//Set pads to change colors when clicked.
	var padsArray = $(".pad");
	setPads();

	function setPads() {
		for (i=0; i < padsArray.length; i++) {
			padsArray[i].onclick = function() {
//				var padID = this.getAttribute("id");
//				var padNumber = /\d/.exec(padID);
				if (this.className === "pad") {
//					activeSoundPattern[padNumber] = 1;
					this.setAttribute('class', "kick"); //HARD CODED FOR KICK TEMPORARILY//
				} else {
//					activeSoundPattern[padNumber] = 0;
					this.setAttribute('class', "pad");	
				}
			}	
		}
	}





	// Set "on" button functions
	// if it's clicked and alreaday on, do nothing
	// if it's clicked and off, set onOff to "on", blink the first pad, then repeat for next pad every sixteenth note 
	// document.getElementById("start").onclick = function() {
	// 	if(onOff === "on") {
	// 		return;
	// 	} else {
	// 		onOff = "on";
	// 		blinkOn();
	// 		// toClearOnOff = setInterval(function(){blinkOn();}, msp16th*padsArray.length);
	// 		toClearOnOff = setInterval(function(){blinkOn();}, msp16th);		
	// 	}
	// }

	// Set the "off" button up.
	// if it's clicked and everything is already off (onOff set to "off"), do nothing.
	// if it's clicked and everything is on, turn it off using the clearInterval function generated by the on button.
	// document.getElementById("stop").onclick = function() {
	// 	if(onOff === "off") {
	// 		return;
	// 	} else {
	// 		onOff = "off";
	// 		currentBeat = 0;
	// 		changePads(activeSound);
	// 		clearInterval(toClearOnOff);
	// 	}
	// }


	// add attributes and onclick behavior to pads

	//setSounds();



	// Generate an array that's equal to the number of pads for each drum sound.
	// Make the pads turn on and off when clicked by assigning an onclick function to each pad.




	// set up each of the sound pads
	// each pad onclick function gets the name of the sound associated with the pad and plays it
	// if it's not the sound that's currently showing on the pads it also calls changePads
	// function setSounds() {
	// 	for (i=0; i < soundsArray.length; i++) {
	// 		soundsArray[i].onclick = function() {
	// 			var soundName = this.id;

	// 			if (activeSound === soundName) {
	// 				var soundPath = "audio/" + soundName + ".wav"
	// 				var snd = new Audio(soundPath);
	// 				snd.play();
	// 			} else {
	// 				changePads (soundName);
	// 				var soundPath = "audio/" + soundName + ".wav"
	// 				var snd = new Audio(soundPath);
	// 				snd.play();
	// 			}
	// 		}	
	// 	}
	// }
});